[package]
name = "taskbar-ip"
version = "1.2.2"
edition = "2021"

[build-dependencies]
embed-manifest = "=1.4.0"

[dependencies]
serde = "=1.0.202"
serde_json = "=1.0.117"
sha2 = "=0.10.8"
winapi = { version = "0.3", features = ["winuser", "wingdi", "libloaderapi", "winreg", "iphlpapi", "consoleapi", "ws2def", "tlhelp32", "handleapi", "processthreadsapi", "fileapi", "errhandlingapi", "winnt", "ntdef", "synchapi", "minwinbase", "winerror", "securitybaseapi", "winhttp"] }

[[bin]]
name = "taskbar-ip"
path = "src/main.rs"

[[bin]]
name = "uninstall"
path = "src/uninstall.rs"

[[bin]]
name = "setup"
path = "src/setup.rs"
